/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package quotes

import io.ktor.application.*
import io.ktor.features.*
import io.ktor.jackson.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import quotes.modules.quotesModule

fun Application.module() {
    install(ContentNegotiation) { jackson() }
    quotesModule()
}

fun main() {
    embeddedServer(Netty, port = 8080, module = Application::module).start()
}
